// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1H9B7lcyLthvZXf1KAtNfmnFNIdh5t8A',
    appId: '1:717253650913:web:c16d3e5d6b4158b1d78aa0',
    messagingSenderId: '717253650913',
    projectId: 'chat-app-8575c',
    authDomain: 'chat-app-8575c.firebaseapp.com',
    storageBucket: 'chat-app-8575c.appspot.com',
    measurementId: 'G-TDK3BPE15Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR2bKP_mCMpB1GcvJIu-KnmRatf4V-o7M',
    appId: '1:717253650913:android:17794de05fbdc956d78aa0',
    messagingSenderId: '717253650913',
    projectId: 'chat-app-8575c',
    storageBucket: 'chat-app-8575c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAVb8efPyu03QUx5l5POmXsYXc3x3_DFA',
    appId: '1:717253650913:ios:473fc4af372e29d8d78aa0',
    messagingSenderId: '717253650913',
    projectId: 'chat-app-8575c',
    storageBucket: 'chat-app-8575c.appspot.com',
    iosClientId: '717253650913-k1tmg3l82jh9u4v1d51ltdci6t9lei5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
